spring.application.name=mini-ecommerce-be
spring.datasource.url=jdbc:h2:mem:ecommerce-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cho phép truy c?p H2 Console t?i http://localhost:8080/h2-console
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update